# check get all user tasks - 200
GET http://localhost:5000/api/users/2/tasks HTTP/1.1

# check get all user tasks - 200
GET http://localhost:5000/api/users/6/tasks HTTP/1.1

# check get all nonexisting user tasks - 404
GET http://localhost:5000/api/users/2000/tasks HTTP/1.1
