#check update existing user - 200
PUT http://localhost:5000/api/users/2 HTTP/1.1
Content-Type: application/json

{
  "firstName":"Secondname",
  "lastName":"Testovych",
  "email":"test10@test.com",
  "passwordHash":"123456",
  "birthday":"2000-02-01",
  "gender":"male"
}

#check create user - 201
PUT http://localhost:5000/api/users/1002 HTTP/1.1
Content-Type: application/json

{
  "firstName":"Secondname",
  "lastName":"Testovych",
  "email":"test13@test.com",
  "passwordHash":"123456",
  "birthday":"2000-02-01",
  "gender":"male"
}